# general, unlikely to change
tokenizer:
    max_length: 128
    padding: true
    truncation: true
    return_tensors: pt
train_batch_size: 32  # can be higher because batches are usually shorter
wikitext_batch_size: 16
retain_batch_size: 16
num_eval_batches: 8  # will make it slower, but for final plots make it bigger
target_modules:
  - gate_proj
  - up_proj
  - down_proj

# model_id: meta-llama/Llama-3.2-3B
# model_id: meta-llama/Llama-3.2-1B
model_id: meta-llama/Llama-3.1-8B

# dataset: wmdp_cyber_pairs
# dataset: wmdp_cyber_pairs_only_ans
# dataset: wmdp_cyber_deebs
dataset: wmdp_cyber_simple
num_examples_per_question: 3
use_dev_split: false

max_num_epochs: 1000

retraining_rate: 3e-5  # even with 1e-6, wikitext_loss has this Nike shape
retraining_epochs: 15
eval_on_all_questions: false

# default experiment config
algorithm: CIR
loss_budget: 1.005
cir_niter: 16
comment: null
mask_n_most_common_tokens: null
# mask_n_most_common_tokens: 50
# eval_on_all_questions: true  # best to just use it when not retraining
#
cut_off_tokens: 1
loss_fn_name: mlp_confuse
layer_range: null
mlp_floor: 0.0

max_norm: 0.05
act_proj_num: 24
grad_proj_num: 36

cb_layers: null
cb_type: dot
cb_floor: 0.0
cb_pow: 1.0
# mlp_retaining_pow: 1.0
# cb_retaining_layers: null

experiment_list:

    - layer_range: [0, 6]
      loss_fn_name: circuit_breaker
    
    - layer_range: [6, 12]
      loss_fn_name: circuit_breaker

    - layer_range: [12, 18]
      loss_fn_name: circuit_breaker

    - layer_range: [18, 24]
      loss_fn_name: circuit_breaker

    - layer_range: [24, 30]
      loss_fn_name: circuit_breaker


    - layer_range: [0, 6]
      loss_fn_name: mlp_confuse
    
    - layer_range: [6, 12]
      loss_fn_name: mlp_confuse

    - layer_range: [12, 18]
      loss_fn_name: mlp_confuse

    - layer_range: [18, 24]
      loss_fn_name: mlp_confuse

    - layer_range: [24, 30]
      loss_fn_name: mlp_confuse


    - layer_range: [0, 6]
      loss_fn_name: circuit_breaker
      algorithm: GA
      max_norm: 0.0003
    
    - layer_range: [6, 12]
      loss_fn_name: circuit_breaker
      algorithm: GA
      max_norm: 0.0003

    - layer_range: [12, 18]
      loss_fn_name: circuit_breaker
      algorithm: GA
      max_norm: 0.0003

    - layer_range: [18, 24]
      loss_fn_name: circuit_breaker
      algorithm: GA
      max_norm: 0.0003

    - layer_range: [24, 30]
      loss_fn_name: circuit_breaker
      algorithm: GA
      max_norm: 0.0003
