# general, unlikely to change
tokenizer:
    max_length: 128
    padding: true
    truncation: true
    return_tensors: pt
train_batch_size: 32  # can be higher because batches are usually shorter
wikitext_batch_size: 16
retain_batch_size: 16
num_eval_batches: 8  # todo in the end change to 16
target_modules:
  - gate_proj
  - up_proj
  - down_proj

# model_id: meta-llama/Llama-3.2-3B
# model_id: meta-llama/Llama-3.2-1B
model_id: meta-llama/Llama-3.1-8B

# dataset: wmdp_cyber_pairs
# dataset: wmdp_cyber_pairs_only_ans
# dataset: wmdp_cyber_deebs
dataset: wmdp_cyber_simple
num_examples_per_question: 3
use_dev_split: false

max_num_epochs: 1000

retraining_rate: 3e-5  # even with 1e-6, wikitext_loss has this Nike shape
retraining_epochs: 15  # todo in the end change to 50
eval_on_all_questions: false

# default experiment config
algorithm: CIR
loss_budget: 1.001
cir_niter: 16
comment: null
mask_n_most_common_tokens: null
# mask_n_most_common_tokens: 50
# eval_on_all_questions: true  # best to just use it when not retraining
#
cut_off_tokens: 1
loss_fn_name: ???
layer_range: null
mlp_floor: 0.0

max_norm: ???
act_proj_num: 24
grad_proj_num: 36
layer_range: [6, 12]

cb_type: dot
cb_floor: 0.0
cb_pow: 1.0
# mlp_retaining_pow: 1.0

retaining_rate: 1e-3
retaining_loss_fns: [cb_retain]
cb_retaining_layers: [12]


experiment_list:
    
    - loss_fn_name: mlp_confuse
      max_norm: 0.005

    - loss_fn_name: mlp_confuse
      max_norm: 0.005
      retaining_rate: 3e-4

    - loss_fn_name: mlp_confuse
      max_norm: 0.002

    - loss_fn_name: mlp_confuse
      max_norm: 0.001

    - loss_fn_name: mlp_confuse
      max_norm: 0.010



    - loss_fn_name: circuit_breaker
      algorithm: GA
      max_norm: 0.005

    - loss_fn_name: circuit_breaker
      algorithm: GA
      max_norm: 0.005
      loss_budget: 1.01



    - loss_fn_name: neg_cross_entropy
      algorithm: GA
      retaining_rate: 3e-5
      retaining_loss_fns: [cross_entropy]
      max_norm: 0.0003
      loss_budget: 1.01

    - loss_fn_name: neg_cross_entropy
      algorithm: GA
      retaining_rate: 1e-5
      retaining_loss_fns: [cross_entropy]
      max_norm: 0.0003
      loss_budget: 1.01

    - loss_fn_name: neg_cross_entropy
      algorithm: GA
      retaining_rate: 0
      retaining_loss_fns: [cross_entropy]
      max_norm: 0.0003
      loss_budget: 1.01

    - loss_fn_name: neg_cross_entropy
      algorithm: GA
      retaining_rate: 1e-4
      retaining_loss_fns: [cross_entropy]
      max_norm: 0.0003
      loss_budget: 1.01





















    # - layer_range: [18, 24]
    #   loss_fn_name: circuit_breaker
    #   algorithm: GA
    #   max_norm: 0.0003
